name: My First Workflows yml 

on : 
  push:
    branches:  
      - main

jobs:
  run-python-app:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v3
            
          - name: Install Dependencies 
            run:  pip install -r requirements.txt

          - name: Run python app
            run: python test.py && python app.py
            
